/**
 * Hardcoded neighborhood list for Accra and Tema.
 * Source: backend/data/neighborhoods.accra.tema.json
 * Selecting a neighborhood auto-populates the city field.
 */

export const ACCRA_NEIGHBORHOODS = [
    'Abbosey Okai',
    'Abeka',
    'Ablekuma North',
    'Accra Central',
    'Achimota',
    'Adabraka',
    'Adenta',
    'Adjiringanor',
    'Agbogbloshie',
    'Airport Hills',
    'Airport Residential',
    'Alajo',
    'Amasaman',
    'Amrahia',
    'Arena',
    'Ashaley Botwe',
    'Asylum Down',
    'Burma Camp',
    'Cantonments',
    'Caprice',
    'Chorkor',
    'Circle',
    'Dansoman',
    'Dodowa Road',
    'Dodowa Township',
    'Dome',
    'Dzorwulu',
    'East Legon',
    'East Legon Hills',
    'Fadama',
    'Haatso',
    'Kanda',
    'Kaneshie',
    'Kasoa',
    'Kasoa Central',
    'Kawukudi',
    'Kokomlemle',
    'Kokrobite',
    'Korle Gonno',
    'Kotobabi',
    'Kwabenya',
    'La',
    'Labadi',
    'Labone',
    'Lakeside Estate',
    'Lapaz',
    'Laterbiokoshie',
    'Maamobi',
    'Mamprobi',
    'McCarthy Hill',
    'New Town',
    'Nima',
    'North Kaneshie',
    'Odorkor',
    'Okaishie',
    'Osu',
    'Oyarifa',
    'Oyibi',
    'Pig Farm',
    'Pokuase',
    'Ridge',
    'Roman Ridge',
    'Shai Hills',
    'Sowutuom',
    'Spintex',
    'Spintex East',
    'Taifa',
    'Teshie-Nungua Estates',
    'Trade Fair',
    'Trasacco Area',
    'Tse Addo',
    'Tudu',
    'Weija',
    'West Trassacco',
    'Westlands',
];

export const TEMA_NEIGHBORHOODS = [
    'Afienya',
    'Ashaiman',
    'Baatsona',
    'Baatsona Estate East',
    'Dawhenya',
    'Free Zone Enclave',
    'Greenwich Meridian',
    'Heavy Industrial Area',
    'Klagon',
    'Kpone',
    'Lashibi',
    'Ningo',
    'Prampram',
    'Sakumono',
    'Tema Community 1',
    'Tema Community 2',
    'Tema Community 3',
    'Tema Community 4',
    'Tema Community 5',
    'Tema Community 6',
    'Tema Community 7',
    'Tema Community 8',
    'Tema Community 9',
    'Tema Community 10',
    'Tema Community 11',
    'Tema Community 12',
    'Tema Community 13',
    'Tema Community 14',
    'Tema Community 15',
    'Tema Community 16',
    'Tema Community 17',
    'Tema Community 18',
    'Tema Community 19',
    'Tema Community 20',
    'Tema Community 21',
    'Tema Community 22',
    'Tema Community 23',
    'Tema Community 24',
    'Tema Community 25',
    'Tema Newtown',
];

/**
 * Helper: given a neighborhood name, return the city ('Accra' or 'Tema')
 */
export const getCityForNeighborhood = (name) => {
    if (!name) return '';
    if (ACCRA_NEIGHBORHOODS.some((n) => n.toLowerCase() === name.toLowerCase())) return 'Accra';
    if (TEMA_NEIGHBORHOODS.some((n) => n.toLowerCase() === name.toLowerCase())) return 'Tema';
    return '';
};
